-- Generated by scripts/world_model/seed_jsonl_to_sql.ts
-- generated_at_utc: 2026-02-16T00:00:00.000Z
-- input_file: scripts/world_model/examples/sample_facts.jsonl
-- rows: 4
--
-- NOTE: This SQL mutates data when executed. Run intentionally via psql.

begin;

with input_rows as (
  select *
  from (
    values
      (1, '11111111-1111-4111-8111-111111111111'::uuid, '2025-09-04T04:00:00.000Z'::timestamptz, '2026-02-16T00:00:00.000Z'::timestamptz, 'scope.feature'::text, '{"confidence":0.9,"feature":"site.alias.primary","tags":["PLANS_GT","ALIAS"],"value":"Enterprise"}'::jsonb, null::uuid, null::text, null::uuid, null::integer, null::integer, 'moss_plan_scrape_20260216'::text, 'seed_run_20260216_a'::text, '{"document":"moss_plan_set","section":"A1","source":"gpt_pro_scrape"}'::jsonb),
      (2, '11111111-1111-4111-8111-111111111111'::uuid, '2025-09-04T04:00:00.000Z'::timestamptz, '2026-02-16T00:00:00.000Z'::timestamptz, 'scope.feature'::text, '{"confidence":0.98,"feature":"space.scullery.exists","tags":["PLANS_GT"],"value":true}'::jsonb, null::uuid, null::text, null::uuid, null::integer, null::integer, 'moss_plan_scrape_20260216'::text, 'seed_run_20260216_a'::text, '{"document":"moss_plan_set","section":"A2","source":"gpt_pro_scrape"}'::jsonb),
      (3, '22222222-2222-4222-8222-222222222222'::uuid, '2025-10-02T12:30:00.000Z'::timestamptz, '2026-02-16T00:00:00.000Z'::timestamptz, 'permit.status'::text, '{"confidence":0.82,"jurisdiction":"Oconee","status":"submitted"}'::jsonb, 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'::uuid, 'cll_06EXAMPLEPREFILLED'::text, 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'::uuid, 12, 67, null::text, null::text, null::jsonb),
      (4, '22222222-2222-4222-8222-222222222222'::uuid, '2025-10-03T15:00:00.000Z'::timestamptz, '2026-02-16T00:00:00.000Z'::timestamptz, 'schedule.milestone'::text, '{"date":"2025-10-20","milestone":"framing_start","status":"planned"}'::jsonb, null::uuid, null::text, null::uuid, null::integer, null::integer, 'hurley_plan_scrape_20260216'::text, 'seed_run_20260216_b'::text, '{"document":"hurley_plan_set","section":"S1","source":"gpt_pro_scrape"}'::jsonb)
  ) as v(
    line_no,
    project_id,
    as_of_at,
    observed_at,
    fact_kind,
    fact_payload,
    provided_evidence_event_id,
    interaction_id,
    source_span_id,
    source_char_start,
    source_char_end,
    source_batch_id,
    source_run_id,
    source_metadata
  )
),
manual_groups as (
  select
    ir.project_id,
    ir.source_batch_id,
    min(ir.as_of_at) as occurred_at_utc,
    max(ir.source_run_id) as source_run_id,
    count(*)::integer as row_count,
    jsonb_agg(ir.source_metadata) filter (where ir.source_metadata is not null) as source_metadata_rollup
  from input_rows ir
  where ir.provided_evidence_event_id is null
  group by ir.project_id, ir.source_batch_id
),
insert_manual_evidence as (
  insert into public.evidence_events (
    source_type,
    source_id,
    transcript_variant,
    occurred_at_utc,
    source_run_id,
    metadata
  )
  select
    'manual',
    concat('manual_seed:world_model_jsonl:', mg.project_id::text, ':', md5(mg.source_batch_id)),
    'baseline',
    mg.occurred_at_utc,
    mg.source_run_id,
    jsonb_build_object(
      'seed_tool', 'scripts/world_model/seed_jsonl_to_sql.ts',
      'seed_kind', 'world_model_seed_jsonl_v0',
      'generated_at_utc', '2026-02-16T00:00:00.000Z'::text,
      'input_file', 'scripts/world_model/examples/sample_facts.jsonl'::text,
      'project_id', mg.project_id::text,
      'source_batch_id', mg.source_batch_id,
      'row_count', mg.row_count,
      'source_metadata_rollup', coalesce(mg.source_metadata_rollup, '[]'::jsonb)
    )
  from manual_groups mg
  on conflict (source_type, source_id, transcript_variant) do nothing
  returning evidence_event_id, source_id
),
resolved_manual as (
  select
    mg.project_id,
    mg.source_batch_id,
    ee.evidence_event_id
  from manual_groups mg
  join public.evidence_events ee
    on ee.source_type = 'manual'
   and ee.source_id = concat('manual_seed:world_model_jsonl:', mg.project_id::text, ':', md5(mg.source_batch_id))
   and ee.transcript_variant = 'baseline'
),
resolved_rows as (
  select
    ir.line_no,
    ir.project_id,
    ir.as_of_at,
    ir.observed_at,
    ir.fact_kind,
    ir.fact_payload,
    coalesce(ir.provided_evidence_event_id, rm.evidence_event_id) as evidence_event_id,
    ir.interaction_id,
    ir.source_span_id,
    ir.source_char_start,
    ir.source_char_end
  from input_rows ir
  left join resolved_manual rm
    on ir.provided_evidence_event_id is null
   and ir.project_id = rm.project_id
   and ir.source_batch_id = rm.source_batch_id
)
insert into public.project_facts (
  project_id,
  as_of_at,
  observed_at,
  fact_kind,
  fact_payload,
  interaction_id,
  evidence_event_id,
  source_span_id,
  source_char_start,
  source_char_end
)
select
  rr.project_id,
  rr.as_of_at,
  rr.observed_at,
  rr.fact_kind,
  rr.fact_payload,
  rr.interaction_id,
  rr.evidence_event_id,
  rr.source_span_id,
  rr.source_char_start,
  rr.source_char_end
from resolved_rows rr
where rr.evidence_event_id is not null
  and not exists (
    select 1
    from public.project_facts pf
    where pf.project_id = rr.project_id
      and pf.as_of_at = rr.as_of_at
      and pf.observed_at = rr.observed_at
      and pf.fact_kind = rr.fact_kind
      and pf.fact_payload = rr.fact_payload
      and pf.evidence_event_id is not distinct from rr.evidence_event_id
      and pf.interaction_id is not distinct from rr.interaction_id
      and pf.source_span_id is not distinct from rr.source_span_id
      and pf.source_char_start is not distinct from rr.source_char_start
      and pf.source_char_end is not distinct from rr.source_char_end
  )
order by rr.line_no;

commit;
